### ISSUE TITLE
Dataset import not working for me

### ISSUE THREAD

**Issue by IC1Rahul** [hedrox/ecg-classification#2]
I get the rdsamp not installed error, but i do have the wfdb  toolbox.

**Comment by hedrox** [comment]
Make sure rdsamp is in your PATH environment variable. So you should be able to see the output of rdsamp -h

**Comment by IC1Rahul** [comment]
How can i set rdsamp in PATH? It is part of WFDB package , the system
recognize the wfdb functions but not rdsamp

**Comment by hedrox** [comment]
I think you should reinstall the package, it should have been in you path.
